'use client';
import { AlertTriangle, CheckCircle2, CircleHelp, RefreshCw } from 'lucide-react';
import { useCase } from '@/components/case-provider';
import { GroundedNote } from '@/components/grounded-note';
import { ViewState } from '@/components/view-state';
import { Badge, Button, PageHeader } from '@/components/ui';

const names={appears_supported:'Appears within supported route',more_information:'More information needed',outside_supported:'Outside supported route'} as const;
// @ts-expect-error The guarded record is stable for this render and its event handlers.
function RoutePage(){const {record,workflow,mutate,toast}=useCase();if(!record||!workflow)return null;const route=workflow.route,stale=route.sourceCaseVersion!==record.version;async function action(kind:'refresh'|'review'){try{await mutate('/api/route',{version:record.version,action:kind});toast(kind==='review'?'Screening marked as reviewed.':'Screening updated from the current case.');}catch(e){toast(e instanceof Error?e.message:'Unable to update screening.')}}return <><PageHeader eyebrow="Stage 5" title="Check the filing route" description="A rules-based screening of the current case record." action={<Badge label={stale?'Needs review':route.reviewed?'Reviewed':'In progress'} tone={stale?'warn':route.reviewed?'good':'neutral'}/>}/><div className="split"><div><section className="section"><div className="row"><div><div className="small muted">Screening result</div><h2 style={{marginTop:5}}>{stale?'Case information changed':names[route.outcome]}</h2></div>{route.outcome==='appears_supported'?<CheckCircle2 size={28} className="icon-good"/>:route.outcome==='more_information'?<CircleHelp size={28} className="icon-warn"/>:<AlertTriangle size={28} className="icon-bad"/>}</div><p className="muted" style={{lineHeight:1.55}}>This screens procedural fit only. It does not assess the merits of your claim or predict an outcome.</p>{stale&&<div className="callout"><AlertTriangle size={19}/><span>This result was based on case version {route.sourceCaseVersion}. Refresh it before relying on the result.</span></div>}<div className="stack" style={{marginTop:24}}>{route.reasons.map((reason,i)=><div className="row" key={`${reason.label}-${i}`} style={{padding:'13px 0',borderBottom:'1px solid var(--line)'}}><span>{reason.label}</span><Badge label={reason.result==='pass'?'Information available':reason.result==='unknown'?'Needs information':'Outside supported scope'} tone={reason.result==='pass'?'good':reason.result==='unknown'?'warn':'bad'}/></div>)}</div><div className="row" style={{marginTop:24,justifyContent:'flex-start'}}><Button kind="primary" onClick={()=>void action('refresh')}><RefreshCw size={16}/>Check current case</Button><Button onClick={()=>void action('review')} disabled={stale}>Mark reviewed</Button></div></section></div><aside className="aside"><h3>How this was checked</h3><p className="small muted">Versioned rules compare the claim type, amount, relevant date, respondent location and exceptional circumstances.</p><GroundedNote assertionId="limits"/><div style={{height:10}}/><GroundedNote assertionId="time"/><div style={{height:10}}/><GroundedNote assertionId="assessment"/></aside></div></>}
export default function Page(){return <ViewState><RoutePage/></ViewState>}
