'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { BookOpen, CircleHelp, ClipboardCheck, FileArchive, FileSearch, FolderOpen, Home, Menu, MessagesSquare, Route, Scale, UserRound, X } from 'lucide-react';
import { useState } from 'react';

const primary=[['/','Overview',Home],['/intake','Explain',MessagesSquare],['/documents','Documents',FolderOpen],['/chronology','Confirm facts',UserRound],['/evidence','Review support',FileSearch],['/options','Choose next step',Route],['/prepare','Prepare & hand off',FileArchive]] as const;
const secondary=[['/sources','Official sources',BookOpen],['/verification','Verification record',ClipboardCheck]] as const;

function Navigation({close}:{close?:()=>void}){const path=usePathname();return <><nav className="side-nav" aria-label="Case stages">{primary.map(([href,label,Icon])=><Link key={href} href={href} onClick={close} className="side-link" aria-current={path===href?'page':undefined}><Icon size={20}/><span>{label}</span></Link>)}</nav><div className="side-spacer"/><div className="side-rule"/><nav className="side-nav" aria-label="References">{secondary.map(([href,label,Icon])=><Link key={href} href={href} onClick={close} className="side-link" aria-current={path===href?'page':undefined}><Icon size={20}/><span>{label}</span></Link>)}</nav></>}

export function Shell({children}:{children:React.ReactNode}){const [mobile,setMobile]=useState(false);return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand">Casepath</Link><Navigation/></aside>{mobile&&<><button className="drawer-scrim" aria-label="Close menu" onClick={()=>setMobile(false)}/><aside className="drawer" style={{left:0,right:'auto'}}><div className="drawer-head"><span className="brand" style={{margin:0}}>Casepath</span><button className="button button-quiet" onClick={()=>setMobile(false)} aria-label="Close menu"><X size={20}/></button></div><div style={{height:24}}/><Navigation close={()=>setMobile(false)}/></aside></>}<main className="main-frame"><header className="topbar"><div className="row-start"><button className="button button-quiet mobile-menu" onClick={()=>setMobile(true)} aria-label="Open menu"><Menu size={21}/></button><div className="topbar-title">Small claims preparation</div></div><div className="topbar-actions"><Link className="button button-quiet" href="/sources"><CircleHelp size={19}/><span>Help</span></Link><span aria-hidden="true" style={{height:30,width:1,background:'var(--line)'}}/><span className="button button-quiet"><Scale size={19}/><span>Demo case</span></span></div></header><div className="content">{children}</div></main></div>}
