'use client';
import { ArrowRight, ClipboardList } from 'lucide-react';
import { useCase } from '@/components/case-provider';
import { GroundedNote } from '@/components/grounded-note';
import { ViewState } from '@/components/view-state';
import { Badge, Button, PageHeader } from '@/components/ui';
import type { Option } from '@/lib/contracts';

const choices:{id:Option;title:string;body:string;tradeoff:string}[]=[
 {id:'gather',title:'Gather more information',body:'Fill gaps and resolve conflicting dates before deciding.',tradeoff:'More certainty, but preparation takes longer.'},
 {id:'settlement',title:'Explore settlement',body:'Consider direct discussion, eNegotiation or eMediation.',tradeoff:'May resolve matters sooner; agreement depends on both parties.'},
 {id:'help',title:'Obtain appropriate help',body:'Prepare a concise brief for legal or court support.',tradeoff:'Useful where legal judgment is needed; access depends on the service.'},
 {id:'file',title:'Prepare to file',body:'Review the draft, supporting material and CJTS handoff checklist.',tradeoff:'Available only where the current route screening is supported.'}
];
// @ts-expect-error The guarded record is stable for this render and its event handlers.
function Options(){const {record,workflow,mutate,toast}=useCase();if(!record||!workflow)return null;const stale=workflow.route.sourceCaseVersion!==record.version;async function choose(id:Option){try{await mutate('/api/tasks',{version:record.version,action:'choose',option:id});toast('Your next step has been saved.');}catch(e){toast(e instanceof Error?e.message:'Unable to save your choice.')}}async function task(id:string,status:string){try{await mutate('/api/tasks',{version:record.version,action:status==='Reviewed'?'reopen':'complete',id});toast(status==='Reviewed'?'Task reopened.':'Task marked reviewed.');}catch(e){toast(e instanceof Error?e.message:'Complete the prerequisite first.')}}return <><PageHeader eyebrow="Stage 5" title="Choose your next step" description="Review the options and decide what fits your situation."/><div className="split"><div><section className="section"><h3>Available options</h3><p className="small muted">No option is selected for you. You can change this choice later.</p><div className="choice-grid">{choices.map(c=>{const disabled=c.id==='file'&&(workflow.route.outcome!=='appears_supported'||stale);return <button key={c.id} disabled={disabled} className={`choice ${workflow.option===c.id?'selected':''}`} onClick={()=>void choose(c.id)}><span className="choice-dot"/><span><strong>{c.title}</strong><span className="small muted" style={{display:'block',marginTop:5}}>{c.body}</span><span className="small" style={{display:'block',marginTop:8}}>{c.tradeoff}</span>{disabled&&<span className="small" style={{display:'block',color:'var(--amber)',marginTop:8}}>Review a supported route before choosing this option.</span>}</span><ArrowRight size={18}/></button>})}</div></section><section className="section"><div className="row"><div><h3>Preparation tasks</h3><p className="small muted">Completed preparation steps do not mean the case is likely to succeed.</p></div><Badge label={`${workflow.tasks.filter(t=>t.status==='Reviewed'&&t.sourceCaseVersion===record.version).length} reviewed`} tone="neutral"/></div><div style={{marginTop:12}}>{workflow.tasks.map(t=>{const taskStale=t.sourceCaseVersion!==record.version;return <div className="attention" key={t.id} style={{padding:'12px 0',minHeight:72}}><ClipboardList size={19} className={taskStale?'icon-warn':'icon-good'}/><div style={{flex:1}}><strong>{t.title}</strong><div className="small muted">{t.purpose}</div></div><Button kind="quiet" disabled={taskStale} onClick={()=>void task(t.id,t.status)}>{taskStale?'Needs review':t.status==='Reviewed'?'Reopen':'Mark reviewed'}</Button></div>})}</div></section></div><aside className="aside"><h3>Before you decide</h3><div className="stack" style={{marginTop:14}}><GroundedNote assertionId="settlement"/><GroundedNote assertionId="help"/></div></aside></div></>}
export default function Page(){return <ViewState><Options/></ViewState>}
